apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qc8e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qc8e
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-qc8e
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qc8e
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qc8e
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xjpu-tenant/rhtap-demo-app/hacbs-test-project-qc8e@sha256:44d1c9f761ccb2ef6b27d902a4d65ce0dd64a8b49f5090cfb97edd6912a99d6b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
