apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-qc8e
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xjpu-tenant/rhtap-demo-app/hacbs-test-project-qc8e@sha256:44d1c9f761ccb2ef6b27d902a4d65ce0dd64a8b49f5090cfb97edd6912a99d6b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
